### PR TITLE
deploy: move DEFAULT_REGISTRY env from local-csi-provisioner to csi-p…

### PR DESCRIPTION
**Pull request by AlbeeSo**
…rovisioner

add DEFAULT_REGISTRY to csi-provisioner container for ossfs image pulling after #1139
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by huww98** [comment]
Consider also remove DEFAULT_REGISTRY from plugin？

**Comment by AlbeeSo** [comment]
> Consider also remove DEFAULT_REGISTRY from plugin？

done

**Review by huww98 — COMMENTED** [review]
/lgtm

better to add `{{- if .Values.csi.oss.enabled }}`?

**Pull request merged**
