### PR TITLE
helm: nas driver no longer needs /mnt

### PR DESCRIPTION
**Pull request by huww98**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

remove hostPath /mnt from controller. It is no longer needed since 33875a5bf3 (refactor nas plugin and support accesspoint).

local driver still needs this for quota path.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/cc @tydra-wang 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mowangdk** [comment]
@tydra-wang ptal

**Comment by tydra-wang** [comment]
The NAS driver stores loopdevice image files under `/mnt/nasplugin.alibabacloud.com` when using the `losetup` mode. However this feature is not enabled by default.

**Comment by huww98** [comment]
We have a case where the user have his own mountpoint on /mnt on the host. /mnt is so common that I think we'd better not use it for our purpose.

**Comment by huww98** [comment]
> Yes, but I suppose losetup would still work even if /mnt is not a hostPath?

This will cause problem when CSI plugin restarts.

But I still think this change is desired. Users who want to enable losetup should add the mount themselves.

**Pull request merged**
