### PR TITLE
disk: cancel waiting for attach/detach when GRPC cancelled

### PR DESCRIPTION
**Pull request by huww98**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The default timeout of external-attacher is only 15s. Timeout is common. We can save some OpenAPI calls after timeout.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mowangdk** [comment]
@huww98 rebase this pr please.

**Comment by huww98** [comment]
@mowangdk  Rebased, ptal again.

**Pull request merged**
