### PR TITLE
build: rewrite dockerfile to distroless

### PR DESCRIPTION
**Pull request by huww98**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Only copy necessary binaries.
Cross compile util-linux.
init container is switched to busybox.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

amd64+arm64 only 144MiB

Note that the partition expansion is known broken. growpart is a shell script, but we don't include shell now.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by huww98** [comment]
/hold
depends on #1057 . We don't have mkdir command now.

**Comment by huww98** [comment]
We still have some more deps to be eliminated:
- [ ] losetup
- [ ] growpart
- [ ] mkdir
- [ ] chmod
- [ ] grep
- [ ] tail
- [ ] nsenter
  - [ ] udevadm
  - [ ] iohub-vfhp-helper
  - [ ] get_dbfs_mount_path
  - [ ] dbfs_get_home_path.sh

**Comment by huww98** [comment]
/unhold
since I've added mkdir.

**Comment by huww98** [comment]
should rebase after #1102 got merged. And remove `blockdev`

**Comment by huww98** [comment]
#1057 is merged, dropping `mkdir`

**Comment by mowangdk** [comment]
/lgtm
/approve

Great job! 👍

**Pull request merged**
