### PR TITLE
disk: add tags to ECS snapshot

### LINKED ISSUE #900: VolumeSnapshotClass tags
Here is the VolumeSnapshotClass, 

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: alibaba-disk-snapshot
driver: diskplugin.csi.alibabacloud.com
deletionPolicy: Delete
```

how can we add Tags for VolumeSnapshotClass, is that supported ?

### PR DESCRIPTION
**Pull request by huww98**
#### What type of PR is this?

/kind feature
/kind design

#### What this PR does / why we need it:

Automatically add 3 more tags to every ECS snapshot:
- ack.aliyun.com: current ACK cluster ID
- csi.alibabacloud.com/snapshot/name
- csi.alibabacloud.com/snapshot/namespace

Also allow users to add custom tags.
User should specify "snapshotTags/tagKey: tagValue" in VolumeSnapshotClass to add tag "tagKey: tagValue".  This design allows arbitrary keys and values, compared with the design of disk tags, which does not allow "," in key or value, or ":" in key.

If this design works fine, we can also implement this on disk tags.

#### Which issue(s) this PR fixes:

Fixes #900 

#### Does this PR introduce a user-facing change?

```release-note
3 more tags are added to every new ECS snapshot:
- ack.aliyun.com: current ACK cluster ID
- csi.alibabacloud.com/snapshot/name
- csi.alibabacloud.com/snapshot/namespace
You can also add custom tag "tagKey: tagValue" by specifying "snapshotTags/tagKey: tagValue" in VolumeSnapshotClass.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by shusaan** [comment]
> @shusaan How do you like this design?
Thank you for this.

it is good just for confirm it will support multiple custom tags, like

`SnapshotTags: "team:dev,user:david"`

**Comment by huww98** [comment]
> it is good just for confirm it will support multiple custom tags, like
> 
> `SnapshotTags: "team:dev,user:david"`

@shusaan with current design, this is written as:
```
snapshotTags/team: dev
snapshotTags/user: david
```

**Comment by shusaan** [comment]
> > it is good just for confirm it will support multiple custom tags, like
> > `SnapshotTags: "team:dev,user:david"`
> 
> @shusaan with current design, this is written as:
> 
> ```
> snapshotTags/team: dev
> snapshotTags/user: david
> ```

This one is good but one suggestion, i think if you apply this pattern `SnapshotTags: "team:dev,user:david"` then it is same as disk tags and tags property will be same for disk and snapshot as well.
 ref link,
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/examples/disk/diskTags/storageclass.yaml

**Comment by huww98** [comment]
Yes, I'm aware of the `diskTags`. but that home-made syntax does not have proper escape mechanism. i.e., we have no way to specify tag `user: "david,bob"`. To avoid such corner cases, I made this new design. I think this is simpler for users and more future-proof.

If this look OK to @mowangdk , I will also implement this on StorageClass.

**Comment by shusaan** [comment]
@mowangdk any ETA for this please?

**Comment by shusaan** [comment]
@mowangdk any update please

**Comment by mowangdk** [comment]
> @mowangdk any update please

we have got a large pr ready to merge , this pr will merged after that. and it may have an impact on the existing logic, and we'll probably merge it around January of next year.

**Comment by shusaan** [comment]
@mowangdk any update please

**Comment by shusaan** [comment]
Thank you @mowangdk  can you please share expected release of this.

**Pull request merged**
