### PR TITLE
disk/device_manager: replace syscall with unix package

### PR DESCRIPTION
**Pull request by huww98**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

docs of syscall recommends the unix package. And latter enables simpler code.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mowangdk** [comment]
Can you paste the syscall doc link on this PR

**Comment by huww98** [comment]
https://pkg.go.dev/syscall

> NOTE: Most of the functions, types, and constants defined in this package are also available in the [golang.org/x/sys](https://pkg.go.dev/golang.org/x/sys) package. That package has more system call support than this one, and most new code should prefer that package where possible.

**Comment by huww98** [comment]
There is one more reason leading to these changes: `unix.Major(rdev), unix.Minor(rdev)` do not have corresponding alternatives in `syscall`, which are in fact a lot more complex than I thought.

**Comment by huww98** [comment]
rebased to resolve compile error.

**Pull request merged**
